
server:
  # 端口号
  port: 8888
  servlet:
    # 应用的访问路径
    context-path: /

# MySQL连接
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/event_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  # redis 配置
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引默认0
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    #自定义前缀
    allow-prefix: true
    prefix: "com:toom:"
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms



mybatis-plus:
  configuration:
    # 打印SQL语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰
    #map-underscore-to-camel-case: true
    #开启主键
    use-generated-keys: true

  # 扫描枚举包
  type-enums-package: com.toom.event_system.Enum
  # 实体类路径
  type-aliases-package: com.toom.event_system.Entity
  # XML路径
  mapper-locations: classpath*:/mapper/**Mapper.xml



